DROP TABLE IF EXISTS CONVERSION;

CREATE TABLE CONVERSION
(
    id               INT AUTO_INCREMENT PRIMARY KEY,
    SOURCE_AMOUNT    DOUBLE       NOT NULL,
    SOURCE_CURRENCY  VARCHAR(250) NOT NULL,
    TARGET_CURRENCY  VARCHAR(250) DEFAULT NULL,
    TRANSACTION_ID   VARCHAR(250) DEFAULT NULL,
    AMOUNT           DOUBLE       DEFAULT NULL,
    TRANSACTION_DATE DATE         DEFAULT NULL
);








